# Generated by Django 5.1.2 on 2024-10-16 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=30)),
                ('location', models.TextField()),
                ('pimage', models.ImageField(blank=True, upload_to='pimages')),
                ('doc', models.FileField(blank=True, upload_to='rdocs')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumeAPI.state')),
            ],
        ),
    ]
